import Head from "next/head";
import { Flex, Text, Center, Input, Button } from "@chakra-ui/react";
import Link from "next/link";
import { useState, useContext } from "react";
import { AuthContext } from "@/contexts/AuthContext";
import { canSSRGuest } from "@/utils/canSSRGuest";

export default function Login() {

    const { signIn } = useContext(AuthContext);

    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');

    async function handleLogin() {

        if(email === "" && password === "") {
            return;
        }

        await signIn({
            email,
            password,
        });
    }

    return (
        <>
            <Head>
                <title>Acesse sua conta</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Flex background="barber.900" height="100vh" alignItems="center" justifyContent="center">
                <Flex width={640} direction="column" p={14} rounded={8}>
                    <Center mb={5}>
                        <Text color="orange.900" fontSize={48} fontWeight="bold">Barber</Text>
                    </Center>

                    <Input
                        background="barber.400"
                        color="barber.100"
                        variant="outline"
                        size="lg"
                        type="email"
                        placeholder="email@email.com"
                        mb={3}
                        value={email}
                        onChange={ (e) => setEmail(e.target.value)}
                    />

                    <Input
                        background="barber.400"
                        color="barber.100"
                        variant="outline"
                        size="lg"
                        type="password"
                        placeholder="***********"
                        mb={6}
                        value={password}
                        onChange={ (e) => setPassword(e.target.value)}
                    />

                    <Button 
                        background="button.cta"
                        mb={6}
                        color="gray.900"
                        size="lg"
                        _hover={{ bg: "#ffb13e" }}
                        onClick={handleLogin}
                        >
                            Acessar
                    </Button>

                    <Center mt={2}>
                        <Link href="/register">
                            <Text 
                                cursor="pointer" 
                                color="barber.100"
                                >
                                    Não possui conta? <strong>Registre-se</strong>
                            </Text>
                        </Link>
                    </Center>

                </Flex>
            </Flex>

        </>
    );
}

export const getServerSideProps = canSSRGuest(async (ctx) => {
    return {
        props: {},
    }
});
