import Head from "next/head";
import { Flex, Text, Button, useMediaQuery } from "@chakra-ui/react";
import Link from "next/link";
import { useEffect, useState } from "react";

export default function Home() {

  const [isMobile, setIsMobile] = useState(false);

  useEffect(() => {
    // Verifica se o código está sendo executado no cliente
    if (typeof window !== "undefined") {
      const mediaQuery = window.matchMedia("(max-width: 500px)");
      setIsMobile(mediaQuery.matches);

      // Adiciona um event listener para detectar mudanças na largura da tela
      const handleChange = () => setIsMobile(mediaQuery.matches);
      mediaQuery.addEventListener("change", handleChange);

      // Limpeza do event listener quando o componente for desmontado
      return () => {
        mediaQuery.removeEventListener("change", handleChange);
      };
    }
  }, []);

  return (
    <>
      <Head>
        <title>Barber - Seu sistema completo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex background="barber.900" height="100vh" alignItems="center" justifyContent="center" direction="column">
        <Flex mb={5} gap={4} direction={isMobile ? "column" : "row"} align={isMobile ? "center" : "flex-start"}>
          <Text color="#FFF" fontSize={isMobile ? "28px" : "4xl"} fontWeight="bold">Bem-vindo ao</Text>
          <Text color="orange.900" fontSize="4xl" fontWeight="bold">Barber!</Text>
        </Flex>
        <Button bg="orange.900">
          <Link style={{ color: "#000 " }} href="/login">Entrar</Link>
        </Button>
      </Flex>

    </>
  );
}
