import Head from "next/head";
import { Flex, Text, Button } from "@chakra-ui/react";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Barber - Seu sistema completo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex background="barber.900" height="100vh" alignItems="center" justifyContent="center" direction="column">
        <Flex mb={5} gap={4}>
        <Text color="#FFF" fontSize={48} fontWeight="bold">Bem-vindo ao</Text>
        <Text color="orange.900" fontSize={48} fontWeight="bold">Barber!</Text>
        </Flex>
        <Button bg="orange.900">
          <Link style={{ color: "#000 "}} href="/login">Entrar</Link>
        </Button>
      </Flex>

    </>
  );
}
